name: Node.js CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ $default-branch ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379
    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Tests
      env:
        TEST: ${{ secrets.TEST }}
        REDIS_PASS: redis123
      run: |
        echo $TEST
        docker run -d -p 6379:6379 redis redis-server --requirepass $REDIS_PASS
        npm run test
